// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQldQUZlv2lPdZFS_CiQ_CCqAt0h4g4PY',
    appId: '1:1013746791690:web:653df3fff0e6b9f10d36f3',
    messagingSenderId: '1013746791690',
    projectId: 'diy-umrah-fyp',
    authDomain: 'diy-umrah-fyp.firebaseapp.com',
    storageBucket: 'diy-umrah-fyp.firebasestorage.app',
    measurementId: 'G-SQW7P74VTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDASCV5UBUofaNm-PwMdzQbgntCTV1-nrI',
    appId: '1:1013746791690:android:6453b5ebbc8db96d0d36f3',
    messagingSenderId: '1013746791690',
    projectId: 'diy-umrah-fyp',
    storageBucket: 'diy-umrah-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_63Ig93lI215ylUOvfFvDHk_2yHU0pPs',
    appId: '1:1013746791690:ios:503ce0192319c7d50d36f3',
    messagingSenderId: '1013746791690',
    projectId: 'diy-umrah-fyp',
    storageBucket: 'diy-umrah-fyp.firebasestorage.app',
    iosBundleId: 'com.iann.umrahtripplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_63Ig93lI215ylUOvfFvDHk_2yHU0pPs',
    appId: '1:1013746791690:ios:766ed0ac7c6350430d36f3',
    messagingSenderId: '1013746791690',
    projectId: 'diy-umrah-fyp',
    storageBucket: 'diy-umrah-fyp.firebasestorage.app',
    iosBundleId: 'com.example.diyUmrahPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQldQUZlv2lPdZFS_CiQ_CCqAt0h4g4PY',
    appId: '1:1013746791690:web:e242e8e56de72c630d36f3',
    messagingSenderId: '1013746791690',
    projectId: 'diy-umrah-fyp',
    authDomain: 'diy-umrah-fyp.firebaseapp.com',
    storageBucket: 'diy-umrah-fyp.firebasestorage.app',
    measurementId: 'G-Y4K42PVRW3',
  );
}
